import 'package:flutter/material.dart';

// --- 1. Core Seed Color Definition ---

// Primary Brand Color (Green representing efficiency/fuel)
const Color fuelWisePrimarySeed = Color(0xFF006C4C); // Retain original brand color for seeding

// Custom Semantic Colors for Logic/Alerts (NOT part of standard ColorScheme)
const Color successFE = Color(0xFF388E3C); 
const Color errorCritical = Color(0xFFD32F2F); 
const Color warningDueSoon = Color(0xFFFBC02D); 


// --- 2. Material 3 Color Schemes (Using Color Seeding) ---

// Generate Harmonious Light ColorScheme
final ColorScheme lightColorScheme = ColorScheme.fromSeed(
  seedColor: fuelWisePrimarySeed,
  brightness: Brightness.light,
);

// Generate Harmonious Dark ColorScheme
// FIX: Using Color.fromSeed generates a good dark primary color, which should be darker 
// than the bright 0xFF70DBAC from the previous iteration.
final ColorScheme darkColorScheme = ColorScheme.fromSeed(
  seedColor: fuelWisePrimarySeed,
  brightness: Brightness.dark,
);


// --- 3. Theme Data Definitions ---

// 3.1. Light Theme (Unchanged)
final ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: lightColorScheme,

  textTheme: TextTheme(
    headlineLarge: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: lightColorScheme.onSurface),
    headlineMedium: TextStyle(fontSize: 22, fontWeight: FontWeight.w600, color: lightColorScheme.onSurface),
    bodyLarge: const TextStyle(fontSize: 16),
  ),

  appBarTheme: AppBarTheme(
    backgroundColor: lightColorScheme.primary,
    foregroundColor: lightColorScheme.onPrimary,
    elevation: 4,
    centerTitle: false,
    titleTextStyle: TextStyle(
      fontSize: 22, 
      fontWeight: FontWeight.bold, 
      color: lightColorScheme.onPrimary, 
    ),
  ),

  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: lightColorScheme.primary,
      foregroundColor: lightColorScheme.onPrimary,
      padding: const EdgeInsets.symmetric(vertical: 14),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    ),
  ),

  inputDecorationTheme: InputDecorationTheme(
    border: const OutlineInputBorder(
      borderRadius: BorderRadius.all(Radius.circular(12)),
    ),
    labelStyle: TextStyle(color: lightColorScheme.onSurfaceVariant),
    focusedBorder: OutlineInputBorder(
      borderRadius: const BorderRadius.all(Radius.circular(12)),
      borderSide: BorderSide(color: lightColorScheme.primary, width: 2),
    ),
  ),
  
  floatingActionButtonTheme: FloatingActionButtonThemeData(
    backgroundColor: lightColorScheme.secondary,
    foregroundColor: lightColorScheme.onSecondary,
  ),
  
  tabBarTheme: TabBarThemeData(
    labelColor: lightColorScheme.onPrimary, 
    unselectedLabelColor: lightColorScheme.onPrimary.withValues(alpha: 0.6), 
    indicatorColor: lightColorScheme.onPrimary, 
  ),
);


// 3.2. Dark Theme (FIXED for a more muted Primary)
final ThemeData darkTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: darkColorScheme, // This scheme's primary is darker due to seeding.

  // --- Component Theming ---

  // 1. AppBar
  appBarTheme: AppBarTheme(
    // AppBar Background will use the darker primary color generated by the seed.
    backgroundColor: darkColorScheme.primary, 
    foregroundColor: darkColorScheme.onPrimary, // Text/Icons will be bright for contrast
    elevation: 4,
    centerTitle: false,
    titleTextStyle: TextStyle(
      fontSize: 22, 
      fontWeight: FontWeight.bold,
      color: darkColorScheme.onPrimary,
    ),
  ),

  // 2. Elevated Buttons
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: darkColorScheme.primary,
      foregroundColor: darkColorScheme.onPrimary,
      padding: const EdgeInsets.symmetric(vertical: 14),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    ),
  ),

  // 3. Input Fields
  inputDecorationTheme: InputDecorationTheme(
    border: const OutlineInputBorder(
      borderRadius: BorderRadius.all(Radius.circular(12)),
    ),
    labelStyle: TextStyle(color: darkColorScheme.onSurfaceVariant),
    focusedBorder: OutlineInputBorder(
      borderRadius: const BorderRadius.all(Radius.circular(12)),
      borderSide: BorderSide(color: darkColorScheme.primary, width: 2),
    ),
  ),
  
  // 4. Floating Action Button
  floatingActionButtonTheme: FloatingActionButtonThemeData(
    backgroundColor: darkColorScheme.secondary,
    foregroundColor: darkColorScheme.onSecondary,
  ),

  // 5. TabBar
  tabBarTheme: TabBarThemeData(
    labelColor: darkColorScheme.onPrimary, 
    unselectedLabelColor: darkColorScheme.onPrimary.withValues(alpha: 0.6), 
    indicatorColor: darkColorScheme.onPrimary,
  ),
);